<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_form-control btn-log bor_48151b</name>
   <tag></tag>
   <elementGuidId>f01fcda2-4f4a-469d-9a78-a6cf09173605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.btn-log.border-grey.int_tel_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aafa0dd9-c927-4ea5-89f1-50afd7776c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>68a9d66f-1102-49dd-94f9-ce49d1cbd417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-log border-grey int_tel_input</value>
      <webElementGuid>5a3dcf67-a032-48bc-bc7d-aea5fff4602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>798bee81-8541-4da4-97a1-8440481d70e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>889b847b-989d-4a1a-b51a-9f4d2fce21bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-0</value>
      <webElementGuid>47ae6dbc-4ed9-42d0-92e1-80458e1567a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>490856f5-4b2c-4b38-a160-25e90e800c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control btn-log border-grey int_tel_input&quot;]</value>
      <webElementGuid>9e344463-733d-4217-9404-c7634a1a768c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>aeeaba6f-e574-4c42-b25a-10e415b0ae50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[5]/div[2]/div/input</value>
      <webElementGuid>13b01eb1-30df-4d58-8170-a106d5f6e122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>cfc46144-4b16-48c2-a8f4-7e91ac030890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '812-345-678']</value>
      <webElementGuid>bbf47801-a062-4903-ad18-f23d5aafb1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
